### ISSUE TITLE
Create DLL or LIB

### ISSUE THREAD

**Issue by Zolodei** [nemequ/doboz#1]
Do not tell me how to build a DLL or LIB so that it can be used in my project?
I am writing on PureBasic.

**Comment by nemequ** [comment]
This is just a read-only mirror of https://bitbucket.org/attila_afra/doboz so it can be used as a git submodule.  You should direct your questions there.

That said, I suspect this is more of a PureBasic question than a Doboz question; you may want to find a PureBasic forum instead.
